### ISSUE TITLE
`README` not up to date

### ISSUE THREAD

**Issue by WeisLeDocto** [KlestDedja/Bellatrex#3]
Hi there !

I tried to follow the instructions given in the `README.md` file for testing the module, but it failed right from the start with the following error:

```python-traceback
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 7, in <module>
ModuleNotFoundError: No module named 'utilities'
```

The problematic lines seem to be these ones:
https://github.com/Klest94/Bellatrex/blob/e56ec80aae24548f704f80bb9123fc6f4e62af8b/README.md#L75-L76

I guess that this part of `README.md` was never updated since 69351d0.
My intent is just to bring it to your attention, as [`tutorial.ipynb`](https://github.com/Klest94/Bellatrex/blob/e56ec80aae24548f704f80bb9123fc6f4e62af8b/tutorial.ipynb) seems the be the new correct way to follow the tutorial (although that is nowhere mentioned).

Cheers,
Weis

**Comment by KlestDedja** [comment]
Hello!

[tutorial.ipynb](https://github.com/Klest94/Bellatrex/blob/main/tutorial.ipynb) is indeed the new way to follow the tutorial. It is now updated with <https://github.com/Klest94/Bellatrex/commit/0e9abccd0a10dcc2c123bd8a54d0c2a2878e711f>
