### ISSUE TITLE
Error running `tutorial.ipynb`

### ISSUE THREAD

**Issue by WeisLeDocto** [KlestDedja/Bellatrex#4]
Following up on #3, I tried to run the tutorial provided in the `tutorial.ipynb` Jupyter Notebook. I was able to follow it successfully until the very last cell, that unfortunately crashes when executed. It gives me the following exception:

```python-traceback
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[8], line 11
      7 preds_distr = np.load("example-data/bin_tutorial_y_train_preds.npy")
      8 axs = plot_rules(rules, preds, baselines, weights, 
      9             max_rulelen=None, other_preds=other_preds, preds_distr=preds_distr,
     10 )
---> 11 axs[0].set_xlim([0,1])
     12 # plt.savefig("visualisation.pdf")

AttributeError: 'numpy.ndarray' object has no attribute 'set_xlim'
```

As indicated, the error seems to be that the `axs` variable is treated as an array of `matplotlib.axes.Axes`, whereas it is actually an array of array of `matplotlib.axes.Axes`. I guess the problem comes from 1ff6da6, where the following change occurred in [`visualisation.py`](https://github.com/Klest94/Bellatrex/blob/e56ec80aae24548f704f80bb9123fc6f4e62af8b/visualisation.py) (around line 199):

```diff
-    return axs
+    return aaxs
```

Replacing `axs[0]` with `axs[0, 0]` in the tutorial fixed the issue and successfully plotted a graph. I'm not sure if it's the tutorial that needs to be updated or the value returned by the `plot_rules` function.

Cheers, 
Weis

**Comment by KlestDedja** [comment]
The ```axs``` object has indeed changed, and the tutorial was not up to date. Should be fixed with <https://github.com/Klest94/Bellatrex/commit/0e9abccd0a10dcc2c123bd8a54d0c2a2878e711f>

Thank you for pointing this out!
