### ISSUE TITLE
Extract method to create rules in txt files

### ISSUE THREAD

**Issue by crearth** [KlestDedja/Bellatrex#8]
In order to easily work with the rules, it could be useful to have the creation of txt files outside the plot_visuals() method in the [LocalMethod_class.py](https://github.com/Klest94/Bellatrex/blob/main-dev/app/bellatrex/LocalMethod_class.py) file. It is a small change to the code to extract the new method.

**Comment by crearth** [comment]
See merge #9

**Comment by KlestDedja** [comment]
Dear @crearth , sounds like a good idea to me.
I merged the request, thank you for the contribution!
